server:
  port: 8090

spring:
  application:
    name: react-demo-basic

  data:
    mongodb:
      database: productdb
      host: localhost
      port: 27017

external:
  discount-api:
    base-url: http://localhost:8085/discount

  inventory-api:
    base-url: http://localhost:8088/inventory
